# Product Optimization & Revenue Contribution Analysis for Afficionado Coffee Roasters

## Import Library's

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import mysql.connector as mc
from sqlalchemy import create_engine,text

## Load csv file

In [2]:
df1 = pd.read_csv(r'E:\Product Optimization & Revenue Contribution Analysis for Afficionado Coffee Roasters\row_data\Afficionado Coffee Roasters - Transactions.csv')

In [4]:
df1['store_id'].unique()

array([5, 8, 3])

## Check shape
* rows 149116
* Columns 11

In [3]:
df.shape

(149116, 11)

## Check Info

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   year              149116 non-null  int64
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 12.5+ MB

## Check dtypes

In [46]:
df.head(5)

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,revenue,indian_price,hour
0,1,2025,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.0,283.50,7
1,2,2025,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2,292.95,7
2,3,2025,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.0,425.25,7
3,4,2025,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.0,189.00,7
4,5,2025,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2,292.95,7

In [45]:
df.dtypes

transaction_id               int64
year                         int64
transaction_time            object
transaction_qty              int64
store_id                     int64
store_location      string[python]
product_id                   int64
unit_price                 float64
product_category    string[python]
product_type        string[python]
product_detail      string[python]
revenue                    float64
indian_price               float64
hour                         int32
dtype: object

## Change Datatypes

In [24]:
df['transaction_time'] = pd.to_datetime(df['transaction_time'], format='%H:%M:%S').dt.time

In [15]:
df['store_location'] = df['store_location'].astype('string')

In [18]:
df = df.astype({
    'product_category' : 'string',
    'product_type' : 'string',
    'product_detail' : 'string'
})

## Create new columns

In [29]:
df['revenue'] = df.transaction_qty * df.unit_price

In [35]:
df['indian_price'] = df.unit_price * 94.5

In [44]:
df['hour'] = pd.to_datetime(df['transaction_time'],format='%H:%M:%S').dt.hour

## Check null values

In [37]:
df.isnull().sum()

transaction_id      0
year                0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
revenue             0
indian_price        0
dtype: int64

## Check duplicate values

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.describe()

,transaction_id,year,transaction_qty,store_id,product_id,unit_price,revenue,indian_price
count,149116.000000,149116.0,149116.000000,149116.000000,149116.000000,149116.000000,149116.000000,149116.000000
mean,74737.371872,2025.0,1.438276,5.342063,47.918607,3.382219,4.686367,319.619735
std,43153.600016,0.0,0.542509,2.074241,17.930020,2.658723,4.227099,251.249287
min,1.000000,2025.0,1.000000,3.000000,1.000000,0.800000,0.800000,75.600000
25%,37335.750000,2025.0,1.000000,3.000000,33.000000,2.500000,3.000000,236.250000
50%,74727.500000,2025.0,1.000000,5.000000,47.000000,3.000000,3.750000,283.500000
75%,112094.250000,2025.0,2.000000,8.000000,60.000000,3.750000,6.000000,354.375000
max,149456.000000,2025.0,8.000000,8.000000,87.000000,45.000000,360.000000,4252.500000

In [40]:
df.head(10)

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,revenue,indian_price
0,1,2025,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,283.500
1,2,2025,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,292.950
2,3,2025,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,425.250
3,4,2025,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,189.000
4,5,2025,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,292.950
5,6,2025,07:22:41,1,5,Lower Manhattan,77,3.00,Bakery,Scone,Oatmeal Scone,3.00,283.500
6,7,2025,07:25:49,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,189.000
7,8,2025,07:33:34,2,5,Lower Manhattan,28,2.00,Coffee,Gourmet brewed coffee,Columbian Medium Roast Sm,4.00,189.000
8,9,2025,07:39:13,1,5,Lower Manhattan,39,4.25,Coffee,Barista Espresso,Latte Rg,4.25,401.625
9,10,2025,07:39:34,2,5,Lower Manhattan,58,3.50,Drinking Chocolate,Hot chocolate,Dark chocolate Rg,7.00,330.750

## Let's analysis

In [ ]:
df['product_category'].nunique()

9

## Let's Convert csv into database

* Create database coffee_roasters_db;

In [51]:
conn = mc.connect(
    host='localhost',
    user='root',
    password='qwe99ewq'
)
cursor = conn.cursor()
cursor.execute('CREATE DATABASE coffee_roasters_db')
for i in cursor.fetchall():
    print(i)

In [2]:
engine = create_engine('mysql+pymysql://root:qwe99ewq@localhost/coffee_roasters_db')

In [23]:
df.to_sql('coffee_roasters_tables',index=False,con=engine,if_exists='replace')

C:\Users\Mohd Noman\AppData\Local\Temp\ipykernel_14328\2307600253.py:1: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql('coffee_roasters_tables',index=False,con=engine,if_exists='replace')

149116

* I have saved df in database

# Analysis & Visualization

In [3]:
df=pd.read_sql('SELECT * FROM coffee_roasters_tables',con=engine)

In [4]:
df.shape

(149116, 14)

In [5]:
df.head(2)

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,revenue,indian_price,hour
0,1,2025,0 days 07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.0,283.50,7
1,2,2025,0 days 07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.2,292.95,7

In [28]:
print(f'''
store_id
{df['store_id'].unique()}
{df['store_id'].nunique()}
-------------------------------------------------------------------------------------------------------------------------------------------
store_location
{df['store_location'].unique()}
{df['store_location'].nunique()}
-------------------------------------------------------------------------------------------------------------------------------------------
product_id
{df['product_id'].unique()}
{df['product_id'].nunique()}
-------------------------------------------------------------------------------------------------------------------------------------------
product_category
{df['product_category'].unique()}
{df['product_category'].nunique()}
-------------------------------------------------------------------------------------------------------------------------------------------
product_type
{df['product_type'].unique()}
{df['product_type'].nunique()}
-------------------------------------------------------------------------------------------------------------------------------------------
product_detail
{df['product_detail'].unique()}
{df['product_detail'].nunique()}
''')

store_id
[5 8 3]
3
-------------------------------------------------------------------------------------------------------------------------------------------
store_location
['Lower Manhattan' "Hell's Kitchen" 'Astoria']
3
-------------------------------------------------------------------------------------------------------------------------------------------
product_id
[32 57 59 22 77 28 39 58 56 33 51 87 47 79 42 61 69 40 43 76 45 71 38 26
 27 29 54 55 24 60 78 44 48 23 46 25 34 36 74 53 41 37 50 72 35 70 73 75
 31 49 52 30 64 12 63  6  9 65 84 19  7  1 17 10  4 15 16  3 20 83 18 21
 13 11  5  2 81 14  8 82]
80
-------------------------------------------------------------------------------------------------------------------------------------------
product_category
['Coffee' 'Tea' 'Drinking Chocolate' 'Bakery' 'Flavours' 'Loose Tea'
 'Coffee beans' 'Packaged Chocolate' 'Branded']
9
-------------------------------------------------------------------------------------------------------------------------------------------
product_type
['Gourmet brewed coffee' 'Brewed Chai tea' 'Hot chocolate' 'Drip coffee'
 'Scone' 'Barista Espresso' 'Brewed Black tea' 'Brewed Green tea'
 'Brewed herbal tea' 'Biscotti' 'Pastry' 'Organic brewed coffee'
 'Premium brewed coffee' 'Regular syrup' 'Herbal tea' 'Gourmet Beans'
 'Organic Beans' 'Sugar free syrup' 'Drinking Chocolate' 'Premium Beans'
 'Chai tea' 'Green beans' 'Espresso Beans' 'Green tea' 'Organic Chocolate'
 'Housewares' 'Black tea' 'House blend Beans' 'Clothing']
29
-------------------------------------------------------------------------------------------------------------------------------------------
product_detail
['Ethiopia Rg' 'Spicy Eye Opener Chai Lg' 'Dark chocolate Lg'
 'Our Old Time Diner Blend Sm' 'Oatmeal Scone' 'Columbian Medium Roast Sm'
 'Latte Rg' 'Dark chocolate Rg' 'Spicy Eye Opener Chai Rg' 'Ethiopia Lg'
 'Earl Grey Lg' 'Ouro Brasileiro shot' 'Serenity Green Tea Lg'
 'Jumbo Savory Scone' 'Lemon Grass Rg' 'Sustainably Grown Organic Lg'
 'Hazelnut Biscotti' 'Cappuccino' 'Lemon Grass Lg'
 'Chocolate Chip Biscotti' 'Peppermint Lg' 'Chocolate Croissant' 'Latte'
 'Brazilian Rg' 'Brazilian Lg' 'Columbian Medium Roast Rg'
 'Morning Sunrise Chai Rg' 'Morning Sunrise Chai Lg'
 'Our Old Time Diner Blend Lg' 'Sustainably Grown Organic Rg'
 'Scottish Cream Scone ' 'Peppermint Rg' 'English Breakfast Rg'
 'Our Old Time Diner Blend Rg' 'Serenity Green Tea Rg' 'Brazilian Sm'
 'Jamaican Coffee River Sm' 'Jamaican Coffee River Lg' 'Ginger Biscotti'
 'Traditional Blend Chai Lg' 'Cappuccino Lg' 'Espresso shot'
 'Earl Grey Rg' 'Ginger Scone' 'Jamaican Coffee River Rg'
 'Cranberry Scone' 'Almond Croissant' 'Croissant' 'Ethiopia Sm'
 'English Breakfast Lg' 'Traditional Blend Chai Rg'
 'Columbian Medium Roast Lg' 'Hazelnut syrup' 'Peppermint' 'Carmel syrup'
 'Ethiopia' 'Organic Decaf Blend' 'Sugar Free Vanilla syrup'
 'Chocolate syrup' 'Dark chocolate' 'Jamacian Coffee River'
 'Brazilian - Organic' 'Morning Sunrise Chai'
 'Guatemalan Sustainably Grown' 'Primo Espresso Roast'
 'Serenity Green Tea' 'Traditional Blend Chai' 'Espresso Roast'
 'Sustainably Grown Organic' 'I Need My Bean! Latte cup'
 'Spicy Eye Opener Chai' 'Chili Mayan' 'English Breakfast' 'Lemon Grass'
 'Columbian Medium Roast' 'Our Old Time Diner Blend'
 'I Need My Bean! T-shirt' 'Earl Grey' 'Civet Cat'
 'I Need My Bean! Diner mug']
80

## Pareto 80/20 analysis karo

In [7]:
quary='''
SELECT product_id,
product_detail,
ROUND(SUM(revenue),2) AS total_revenue
FROM coffee_roasters_tables
GROUP BY product_id,
product_detail
ORDER BY total_revenue DESC;'''
pa_revenue=pd.read_sql(quary,con=engine)
pa_revenue

    product_id                product_detail  total_revenue
0           61  Sustainably Grown Organic Lg       21151.75
1           59             Dark chocolate Lg       21006.00
2           39                      Latte Rg       19112.25
3           41                 Cappuccino Lg       17641.75
4           55       Morning Sunrise Chai Lg       17384.00
..         ...                           ...            ...
75          11                   Lemon Grass        1360.40
76          10  Guatemalan Sustainably Grown        1340.00
77          18         Spicy Eye Opener Chai        1335.90
78          14                     Earl Grey        1270.90
79          19                Dark chocolate         755.20

[80 rows x 3 columns]

In [ ]:
df['product_detail'].unique()
df['product_detail'].nunique()

80

In [30]:
df['product_id'].unique()
df['product_id'].nunique()

80